spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.222.251.3:25647/pipilong_personal_blob
      username: pipilong
      password: ZSLnlshb2623

  redis:
    host: localhost
    port: 6379
    password: ZSLnlshb2623
    jedis:
      pool:
        enabled: true
        max-active: 16
  rabbitmq:
    host: 172.17.0.2

es:
  hostAndPort: "172.17.0.3:9200"


logging:
  file:
    path: \root\pipilong\PipilongPersonalBlog\Log.log