spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pipilong-personal_blob
      username: root
      password: 26237447


logging:
  file:
    path: C:\Users\皮皮龙\Desktop\皮皮龙个人博客网站\PipilongPersonalBlog.log