spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pipilong-personal_blob
      username: root
      password: 26237447
  redis:
    host: 101.43.24.234
    port: 6379
    password: ZSLnlshb2623
    jedis:
      pool:
        enabled: true
        max-active: 16
  rabbitmq:
    host: 192.168.43.148

es:
  hostAndPort: "localhost:9200"


logging:
  file:
    path: C:\Users\皮皮龙\Desktop\皮皮龙个人博客网站\PipilongPersonalBlog.log