spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pipilong-personal_blob
      username: root
      password: 26237447
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        enabled: true
        max-active: 16
  rabbitmq:
    host: localhost



es:
  hostAndPort: "localhost:9200"


logging:
  file:
    path: C:\Users\皮皮龙\Desktop\皮皮龙个人博客网站\PipilongPersonalBlog.log